<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.F39mKA7' shared service.

return $this->privates['.service_locator.F39mKA7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\BlogController::add' => ['privates', '.service_locator.SNtE8gu', 'get_ServiceLocator_SNtE8guService.php', true],
    'App\\Controller\\BlogController::renderUserPosts' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\UsersController::register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\BlogController:add' => ['privates', '.service_locator.SNtE8gu', 'get_ServiceLocator_SNtE8guService.php', true],
    'App\\Controller\\BlogController:renderUserPosts' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\UsersController:register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
], [
    'App\\Controller\\BlogController::add' => '?',
    'App\\Controller\\BlogController::renderUserPosts' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\UsersController::register' => '?',
    'App\\Controller\\BlogController:add' => '?',
    'App\\Controller\\BlogController:renderUserPosts' => '?',
    'App\\Controller\\SecurityController:login' => '?',
    'App\\Controller\\UsersController:register' => '?',
]);
