<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.SNtE8gu.Symfony\Component\Security\Core\User\UserInterface' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\security-core\\User\\UserInterface.php';

return $this->privates['.errored..service_locator.SNtE8gu.Symfony\\Component\\Security\\Core\\User\\UserInterface'] = new \Symfony\Component\Security\Core\User\UserInterface();
